### ISSUE TITLE
Exception Unhandled Error

### ISSUE THREAD

**Issue by caniggia1** [umby24/ManagedSockets#1]
HI,
this is great small and simple sockets implementations.
But i have one problem with Client(Viewer project):
if i try to connect to nonexisting IP or nonexisting port(on existing IP) i get this exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'
on this line:
https://github.com/umby24/ManagedSockets/blob/master/sockets/ClientSocket.cs#L272

Can you PLEASE give any advice how to overcome this exception?
Any halp would be appreciated.

BR
caniggia

**Comment by umby24** [comment]
Hey! Thanks for the interest.
Do you have an example of running into that exception?

I'm able to get an exception on that line, but it's a socket exception mentioning the machine listed refused the connection (given a closed port), or I get a timeout exception (given an unroutable IP Address), both of which are expected behavior.

I'll go ahead and add some unit tests to cover a couple of those cases.

**Comment by caniggia1** [comment]
Hey, thanks for your reply.

I've just downloaded your Viewer project, opened it in Visual Studio Community 2017
and start Debuger on Viewer.
I've put into textbox non-existing IP on my network (192.168.10.150) and clicked on Connect Button .
Or i've put into textbox existing IP on my network (192.168.10.151) but closed port(6667) and clicked on Connect Button.
Both times i get 'Exception Unhandled' and if i continue(F10) program just crashes.

I cannot handle this error even if i add this to 'button1_Click':
```
try {
    _mySock.Connect();
} catch {
    WriteToBox("Connection Timeout");
}
```
BR
caniggia

**Comment by umby24** [comment]
reproduced and confirmed the issue.

I created some code (in the commit referenced above) that should cover this.

Strangely enough it doesn't fire in unit tests, so I have that commented out for now, but please pull the latest and see if this covers your issue.

**Comment by caniggia1** [comment]
Hey, that solved my issues.
From now on i dont have to mess around anymore with c# sokets, I'm just gonna use your library.
It fits all my needs and it's so easy to use :)
Thanks Man.

BR
caniggia

**Comment by umby24** [comment]
Sweet! Enjoy!
